version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
http:
    addr: :5000
proxy:
  #remoteurl: https://registry-1.docker.io
  remoteurl: https://plfmv1h0.mirror.aliyuncs.com
