registry:
  container_name: registry
  image: registry:2
  restart: always
  ports:
    - 5000:5000
  volumes:
    - ./config.yml:/etc/docker/registry/config.yml
    - ./data:/var/lib/registry
  environment:
    - TZ='Asia/Shanghai'

docker-registry-ui:
  restart: always
  image: konradkleine/docker-registry-frontend:v2
  ports:
    - "8080:80"
  links:
    - registry:harbor.wallbase.tv
  environment:
    - ENV_DOCKER_REGISTRY_HOST=registry
    - ENV_DOCKER_REGISTRY_PORT=5000

